common: &common
  adapter: mysql2
  username: root
  encoding: utf8
  
development:
  << : *common
  database: taxomatic

production:
  << : *common
  database: taxomatic
    
test:
  << : *common
  database: taxomatic_test