# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 16) do

  create_table "clients", :force => true do |t|
    t.column "name",          :string,  :limit => 45
    t.column "person",        :string,  :limit => 45, :default => "", :null => false
    t.column "email_address", :string
    t.column "phone",         :string
    t.column "address",       :string
    t.column "is_active",     :boolean
  end

  create_table "domains", :force => true do |t|
    t.column "name",       :string
    t.column "created_on", :date
    t.column "website_id", :integer
    t.column "is_free",    :boolean
  end

  create_table "expense_categories", :force => true do |t|
    t.column "name",           :string,  :limit => 100, :default => "", :null => false
    t.column "default_tax",    :integer, :limit => 5,   :default => 0,  :null => false
    t.column "default_amount", :integer, :limit => 5,   :default => 0,  :null => false
    t.column "note",           :string,                 :default => "", :null => false
    t.column "amortization",   :boolean
  end

  add_index "expense_categories", ["name"], :name => "name_unique", :unique => true

  create_table "invoice_numbers", :force => true do |t|
  end

  create_table "payments", :force => true do |t|
    t.column "amount_net",          :integer,   :limit => 8
    t.column "tax",                 :integer,   :limit => 3
    t.column "updated_at",          :timestamp
    t.column "billed_on",           :date
    t.column "description",         :string
    t.column "ref_nr",              :string,    :limit => 100
    t.column "amount_gross",        :integer,   :limit => 8
    t.column "expense_category_id", :integer,   :limit => 5
    t.column "created_at",          :timestamp
    t.column "interval",            :string,    :limit => 45
    t.column "type",                :string,    :limit => 45,  :default => "", :null => false
    t.column "client_id",           :integer,   :limit => 5
    t.column "paid_on",             :date
    t.column "canceled",            :integer,   :limit => 3
    t.column "tax_declaration_id",  :integer
    t.column "website_id",          :integer
  end

  add_index "payments", ["ref_nr"], :name => "ref_nr unique", :unique => true

  create_table "reminders", :force => true do |t|
    t.column "invoice_id", :integer
    t.column "created_on", :date
  end

  create_table "websites", :force => true do |t|
    t.column "name",         :string
    t.column "client_id",    :integer
    t.column "created_on",   :date
    t.column "ftp_username", :string
    t.column "ftp_password", :string
    t.column "hosting_fee",  :integer
  end

end
